# Generated by Django 4.1 on 2022-09-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0003_consumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': 'Sensores'},
        ),
        migrations.AddField(
            model_name='consumo',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swenergy.sensor'),
        ),
    ]
