# Generated by Django 4.1 on 2022-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0004_alter_sensor_options_consumo_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='tipo',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
