# Generated by Django 3.2.15 on 2022-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0004_alter_sensor_options_consumo_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='tipo',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
