# Generated by Django 4.1.1 on 2022-11-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0006_auto_20220919_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('Co2', models.FloatField(null=True)),
                ('KWh', models.FloatField(null=True)),
                ('econimico', models.FloatField(null=True)),
                ('meta', models.FloatField(null=True)),
                ('area', models.FloatField(null=True)),
                ('pupulacao', models.FloatField(null=True)),
                ('pavimentos', models.FloatField(null=True)),
                ('PotInst', models.FloatField(null=True)),
                ('geracaoFV', models.BooleanField(default=False)),
                ('idade', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='predio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swenergy.predio'),
        ),
    ]
