# Generated by Django 4.1.1 on 2022-11-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0007_predio_sensor_predio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predio',
            old_name='econimico',
            new_name='economico',
        ),
    ]
