# Generated by Django 4.1.3 on 2022-12-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0008_rename_econimico_predio_economico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='fim',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='inicio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
