# Generated by Django 4.1.3 on 2022-12-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0008_rename_econimico_predio_economico'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='media',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='consumo',
            name='tipo',
            field=models.CharField(default='diario', max_length=6),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fim',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='inicio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
