# Generated by Django 4.1.3 on 2022-12-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0009_consumo_media_consumo_tipo_alter_consumo_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('Iluminação', models.CharField(max_length=1)),
                ('CondAr', models.CharField(max_length=1)),
                ('envoltoria', models.CharField(max_length=1)),
                ('predio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swenergy.predio')),
            ],
        ),
    ]
