# Generated by Django 4.1.4 on 2022-12-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0010_eficiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='CondAr',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='Iluminação',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='envoltoria',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
