# Generated by Django 4.1.3 on 2022-12-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0011_predio_condar_predio_iluminação_predio_envoltoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predio',
            old_name='Iluminação',
            new_name='Iluminacao',
        ),
    ]
