# Generated by Django 4.1.4 on 2022-12-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0012_rename_iluminação_predio_iluminacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifaNP', models.FloatField(null=True)),
                ('tarifaFP', models.FloatField(null=True)),
                ('NP', models.FloatField(null=True)),
                ('FP', models.FloatField(null=True)),
                ('consumo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='swenergy.consumo')),
            ],
        ),
    ]
