# Generated by Django 4.1.4 on 2022-12-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0013_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='tarifaFP',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='tarifaNP',
            field=models.FloatField(null=True),
        ),
    ]
