# Generated by Django 4.1.4 on 2022-12-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0014_predio_tarifafp_predio_tarifanp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predio',
            old_name='pupulacao',
            new_name='populacao',
        ),
    ]
