# Generated by Django 4.1.4 on 2022-12-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0015_rename_pupulacao_predio_populacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='data',
            field=models.DateField(),
        ),
    ]
