# Generated by Django 4.1.4 on 2022-12-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swenergy', '0016_alter_consumo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
